# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Summary(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, idmap: str=None, frequency: int=None):
        """
        Summary - a model defined in Swagger

        :param id: The id of this Summary.
        :type id: str
        :param idmap: The idmap of this Summary.
        :type idmap: str
        :param frequency: The frequency of this Summary.
        :type frequency: int
        """
        self.swagger_types = {
            'id': str,
            'idmap': str,
            'frequency': int
        }

        self.attribute_map = {
            'id': 'id',
            'idmap': 'idmap',
            'frequency': 'frequency'
        }

        self._id = id
        self._idmap = idmap
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'Summary':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Summary of this Summary.
        :rtype: Summary
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this Summary.
        the type  

        :return: The id of this Summary.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this Summary.
        the type  

        :param id: The id of this Summary.
        :type id: str
        """

        self._id = id

    @property
    def idmap(self) -> str:
        """
        Gets the idmap of this Summary.
        The URL to execute the exactmatches API call on the id

        :return: The idmap of this Summary.
        :rtype: str
        """
        return self._idmap

    @idmap.setter
    def idmap(self, idmap: str):
        """
        Sets the idmap of this Summary.
        The URL to execute the exactmatches API call on the id

        :param idmap: The idmap of this Summary.
        :type idmap: str
        """

        self._idmap = idmap

    @property
    def frequency(self) -> int:
        """
        Gets the frequency of this Summary.
        the number of instances of the specified type 

        :return: The frequency of this Summary.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: int):
        """
        Sets the frequency of this Summary.
        the number of instances of the specified type 

        :param frequency: The frequency of this Summary.
        :type frequency: int
        """

        self._frequency = frequency

